title: Learning Github Pages with Jekyll
author: Tara Dunlop
email: your-email@domain.com
description: Learning Github Pages with Jekyll
theme: minima
plugins:
  - jekyll-feed

# social links
twitter_username: TaraNotChizuye # DO NOT include the @ character, or else the build will fail!
github_username:  taradunlop # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
