title: Tara Dunlop
author: Tara Dunlop
email: your-email@domain.com
description: what i've been doing: training and certifications
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
